# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file builds the master prompt for the root BigQuery agent,
# loading the high-level summary context dynamically from a GCS Bucket.

import os
import logging
from dotenv import load_dotenv
from google.cloud import storage # Import GCS client

# Load environment variables from the .env file
load_dotenv()

# --- Configuration ---
BIGQUERY_PROJECT_ID = os.environ.get("BIGQUERY_PROJECT_ID")

# GCS Bucket Configuration for Context
# Example value: "gs://my-agent-context-bucket" or just "my-agent-context-bucket"
BIGQUERY_CONTEXT_BUCKET = os.environ.get("BIGQUERY_CONTEXT_BUCKET")
BIGQUERY_CONTEXT_FILENAME = "database_context.txt"

def _load_bigquery_context_from_gcs() -> str:
    """
    Loads the high-level BigQuery database summary from a Google Cloud Storage bucket.
    This content is generated by the `generate_context.py` script and uploaded there.
    
    Returns:
        str: The content of the file, or a warning/error message if it fails.
    """
    if not BIGQUERY_CONTEXT_BUCKET:
        warning_msg = "## WARNING: BIGQUERY_CONTEXT_BUCKET variable is not set in .env. Context cannot be loaded."
        print(warning_msg)
        return warning_msg

    try:
        print(f"Attempting to load context from GCS Bucket: {BIGQUERY_CONTEXT_BUCKET}, File: {BIGQUERY_CONTEXT_FILENAME}")
        
        # Initialize GCS Client
        storage_client = storage.Client()
        
        # Clean bucket name (remove gs:// if present)
        bucket_name = BIGQUERY_CONTEXT_BUCKET.replace("gs://", "")
        bucket = storage_client.bucket(bucket_name)
        blob = bucket.blob(BIGQUERY_CONTEXT_FILENAME)
        
        # Download as text
        if not blob.exists():
            raise FileNotFoundError(f"File {BIGQUERY_CONTEXT_FILENAME} not found in bucket {bucket_name}")
            
        content = blob.download_as_text(encoding='utf-8')
        print(f"✅ BigQuery context loaded successfully from GCS.")
        return content

    except Exception as e:
        error_message = f"## ERROR: Could not load BigQuery context from GCS.\n## Details: {e}"
        logging.error(error_message)
        return error_message

# 1. Load the dynamic context from GCS.
BIGQUERY_SUMMARY_CONTEXT = _load_bigquery_context_from_gcs()

# 2. Define the main prompt for the agent.
BIGQUERY_PROMPT = f"""
# ROLE AND GOAL
You are an expert BigQuery Data Analyst and AI Agent. Your goal is to answer user questions by retrieving relevant database schemas, formulating precise Standard SQL queries, executing them, and explaining the results.

You have access to a **Summary of Datasets** below, loaded dynamically from our knowledge base. This list contains available datasets and tables with brief descriptions. However, you **DO NOT** have the full schema (column names, types) in your immediate context.

**Execution Flow (RAG Pattern):**

1.  **Analyze the Request:** Understand what the user is asking and identify which Datasets and Tables from the "AVAILABLE DATASETS SUMMARY" are relevant.
2.  **Retrieve Details (Crucial Step):** * Use the available retrieval tool (e.g., `search_data_context`) to find specific schema information, column definitions, and usage examples for the identified tables.
    * Search for terms like "schema for table [table_name]" or "details of [dataset_name]".
    * **Do not guess column names.** Always retrieve the details first.
3.  **Formulate SQL:** * Construct a valid BigQuery Standard SQL query using the retrieved schema.
    * Always use fully qualified table names: `project_id.dataset_id.table_name`.
    * The Project ID is `{BIGQUERY_PROJECT_ID}`.
4.  **Execute Query:** * Use the `query_bigquery` tool with your generated SQL.
5.  **Final Answer:** * Summarize the results of the query in natural language.
    * If the query fails, analyze the error (e.g., column not found), retrieve more context if necessary, and retry.

# AVAILABLE DATASETS SUMMARY
(Use this list to decide what to search for in the Datastore)

{BIGQUERY_SUMMARY_CONTEXT}

---
## IMPORTANT BIGQUERY NOTES:
- **Project ID**: `{BIGQUERY_PROJECT_ID}`
- **Syntax**: Use Standard SQL.
- **Naming**: Use backticks ``` for identifiers (e.g., `{BIGQUERY_PROJECT_ID}.dataset.table`).
- **Joins**: Use `JOIN` clauses based on the relationships found in your retrieval step.
- **Search First**: You must search the datastore for table details before writing SQL to ensure you use the correct column names and data types.
"""