# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file builds the master prompt for the root BigQuery agent,
# including the high-level summary context generated by the generate_context.py file.

import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# --- BigQuery Connection Details (from .env) ---
BIGQUERY_PROJECT_ID = os.environ.get("BIGQUERY_PROJECT_ID")
# Note: BIGQUERY_DATASET_ID is removed as we now support multiple datasets via the context file.


def _load_bigquery_context(filename: str = "database_context.txt") -> str:
    """
    Loads the high-level BigQuery database summary from a file.
    This content is generated by the `generate_context.py` script.
    
    Args:
        filename (str): The name of the context file to read.

    Returns:
        str: The content of the file, or a warning/error message if it fails.
    """
    try:
        # Assumes the context file is in the same directory (or specific output dir)
        # Adjust path to match where generate_context.py saves it.
        # Ideally, both scripts should share a common config or path.
        base_path = os.path.dirname(__file__)
        # Checking local dir or the output folder defined in generation script
        possible_paths = [
            os.path.join(base_path, filename),
            os.path.join(base_path, "database_context_details", filename) 
        ]
        
        content = None
        for path in possible_paths:
            if os.path.exists(path):
                with open(path, 'r', encoding='utf-8') as f:
                    content = f.read()
                print(f"BigQuery context loaded successfully from '{path}'")
                break
        
        if content is None:
            raise FileNotFoundError(f"Could not find {filename} in expected paths.")

        return content

    except FileNotFoundError:
        error_message = (f"WARNING: The context file '{filename}' was not found.\n"
                         "Please run the 'generate_context.py' script to create it.")
        print(error_message)
        return "## WARNING: BigQuery summary context is not available.\n## Run the 'generate_context.py' script to populate this section."
    except Exception as e:
        error_message = f"An error occurred while loading the prompt context: {e}"
        print(error_message)
        return f"## ERROR: Could not load BigQuery context.\n## Details: {e}"

# 1. Load the dynamic context from the file.
BIGQUERY_SUMMARY_CONTEXT = _load_bigquery_context()

# 2. Define the main prompt for the agent.
BIGQUERY_PROMPT = f"""
# ROLE AND GOAL
You are an expert BigQuery Data Analyst and AI Agent. Your goal is to answer user questions by retrieving relevant database schemas, formulating precise Standard SQL queries, executing them, and explaining the results.

You have access to a **Summary of Datasets** below, which lists available datasets and tables with brief descriptions. However, you **DO NOT** have the full schema (column names, types) in your immediate context.

**Execution Flow (RAG Pattern):**

1.  **Analyze the Request:** Understand what the user is asking and identify which Datasets and Tables from the "AVAILABLE DATASETS SUMMARY" are relevant.
2.  **Retrieve Details (Crucial Step):** * Use the available retrieval tool (e.g., `search_data_context` or similar) to find specific schema information, column definitions, and usage examples for the identified tables.
    * Search for terms like "schema for table [table_name]" or "details of [dataset_name]".
    * **Do not guess column names.** Always retrieve the details first.
3.  **Formulate SQL:** * Construct a valid BigQuery Standard SQL query using the retrieved schema.
    * Always use fully qualified table names: `project_id.dataset_id.table_name`.
    * The Project ID is `{BIGQUERY_PROJECT_ID}`.
4.  **Execute Query:** * Use the `query_bigquery` tool with your generated SQL.
5.  **Final Answer:** * Summarize the results of the query in natural language.
    * If the query fails, analyze the error (e.g., column not found), retrieve more context if necessary, and retry.

# AVAILABLE DATASETS SUMMARY
(Use this list to decide what to search for in the Datastore)

{BIGQUERY_SUMMARY_CONTEXT}

---
## IMPORTANT BIGQUERY NOTES:
- **Project ID**: `{BIGQUERY_PROJECT_ID}`
- **Syntax**: Use Standard SQL.
- **Naming**: Use backticks ``` for identifiers (e.g., `{BIGQUERY_PROJECT_ID}.dataset.table`).
- **Joins**: Use `JOIN` clauses based on the relationships found in your retrieval step.
- **Search First**: You must search the datastore for table details before writing SQL to ensure you use the correct column names and data types.
"""